Hinzufügen von Datumsconstraint zu MedicationDispense
gematik/fhir-profiles-erp pull request #31
Opened 2024-04-10 05:12 UTC by florianschoffke

Als Ergänzung zur Veröffentlichung der Workflow Profile sollen die AFOs A_22073 und A_24282 abgelöst und durch einen FHIR-Constraint ersetzt werden.

Dieser PR fügt die Constraints für
MedicationDispense.whenHandedOver und
MedicationDispense.whenPrepared

ein.

Es wurden auch INVALID Beispiele in der fsh File hinzugefügt, die lokal dann getestet werden können.

2024-04-10 06:15 UTC, Hendrejvr approved these changes

2024-04-11 06:07 UTC, SvenSommer commented on Resources/input/fsh/profiles/GEM_ERP_PR_MedicationDispense.fsh
> +* expression = "toString().length()=10"
Warum wird nur die Länge überprüft und nicht das komplette Datetime format?
e.g.
`* expression = "/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/"`

2024-04-11 06:08 UTC, SvenSommer requested changes

2024-04-11 06:08 UTC, SvenSommer commented on Resources/input/fsh/profiles/GEM_ERP_PR_MedicationDispense.fsh
> +Instance: INVALID-DATE-Example-MedicationDispense-1
Was passiert mir diesen Invarianten, werden sie zu Testzwecken benötigt? Sollten Sie im Examples Repo zur Verfügung gestellt werden?

2024-04-11 08:07 UTC, florianschoffke commented on Resources/input/fsh/profiles/GEM_ERP_PR_MedicationDispense.fsh
> +* expression = "toString().length()=10"
Diese Lösung wurde von der KBV umgesetzt und DAV vorgeschlagen.

2024-04-11 08:08 UTC, florianschoffke commented on Resources/input/fsh/profiles/GEM_ERP_PR_MedicationDispense.fsh
> +Instance: INVALID-DATE-Example-MedicationDispense-1
Da haben wir noch keine einheitliche Linie dazu. Bisher wollten wir vermeiden, dass diese Beispiele auf Simplifier landen. Daher habe ich es auskommentiert.

2024-04-12 12:58 UTC, SvenSommer approved these changes

2024-04-15 04:58 UTC, merged